import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

final lightTheme = ThemeData(
  useMaterial3: true,
  colorScheme: ColorScheme.light(
    primary: Color(0xFF7B61FF),
    onPrimary: Colors.white,
    primaryContainer: Color(0xFFB28DFF),
    onPrimaryContainer: Colors.black,
    primaryFixed: Color(0xFF5A41D1),
    primaryFixedDim: Color(0xFF3E2A9E),
    onPrimaryFixed: Colors.white,
    secondary: Color(0xFF00C4CC),
    onSecondary: Colors.white,
    secondaryContainer: Color(0xFFE0FFFF),
    onSecondaryContainer: Colors.black,
    tertiary: Color(0xFFFFC107),
    onTertiary: Colors.black,
    tertiaryContainer: Color(0xFFFFF3CD),
    onTertiaryContainer: Colors.black,
    error: Color(0xFFFF6B6B),
    onError: Colors.white,
    errorContainer: Color(0xFFFFECEC),
    onErrorContainer: Color(0xFFFF6B6B),
    surface: Colors.white,
    onSurface: Colors.black,
    background: Colors.white,
    onBackground: Colors.black,
    surfaceVariant: Color(0xFFF5F5F5),
  ),
  textTheme: GoogleFonts.nunitoTextTheme(),
  inputDecorationTheme: InputDecorationTheme(
    border: UnderlineInputBorder(borderSide: BorderSide(color: Color(0xFF7B61FF))),
    focusedBorder: UnderlineInputBorder(borderSide: BorderSide(color: Color(0xFF7B61FF))),
    labelStyle: TextStyle(color: Colors.black),
    hintStyle: TextStyle(color: Colors.black54),
  ),
  appBarTheme: AppBarTheme(
    backgroundColor: Color(0xFF7B61FF),
    foregroundColor: Colors.white,
    titleTextStyle: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
  ),
);

final darkTheme = ThemeData(
  useMaterial3: true,
  colorScheme: ColorScheme.dark(
    primary: Color(0xFF5A41D1),
    onPrimary: Colors.white,
    primaryContainer: Color(0xFF3E2A9E),
    onPrimaryContainer: Colors.white,
    secondary: Color(0xFF7B61FF),
    onSecondary: Colors.white,
    secondaryContainer: Color(0xFF5A41D1),
    onSecondaryContainer: Colors.white,
    tertiary: Color(0xFF00C4CC),
    onTertiary: Colors.black,
    tertiaryContainer: Color(0xFF298F6B),
    onTertiaryContainer: Colors.white,
    error: Color(0xFFFF6B6B),
    onError: Colors.white,
    surface: Color(0xFF121212),
    onSurface: Colors.white,
    background: Color(0xFF121212),
    onBackground: Colors.white,
  ),
  textTheme: GoogleFonts.nunitoTextTheme(ThemeData.dark().textTheme),
  appBarTheme: AppBarTheme(
    backgroundColor: Color(0xFF5A41D1),
    foregroundColor: Colors.white,
    titleTextStyle: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
  ),
);